# Configuração do Streamlit
# Este arquivo é carregado automaticamente pelo Streamlit

# Supabase
SUPABASE_URL = "https://zprocqmlefzjrepxtxko.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwcm9jcW1sZWZ6anJlcHh0eGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MDQ2MzksImV4cCI6MjA1NDQ4MDYzOX0.d8-tZf69tPDxYpQOIrJdX6_UG3v6AjEJ-o0ujO9Xv1U"

# Google Maps API
GOOGLE_API_KEY = "AIzaSyCws8dm1mPhPKdu4VUk7BTBEe25qGZDrb4"
