# Configuração do Streamlit
# Este arquivo é carregado automaticamente pelo Streamlit

# Supabase
SUPABASE_URL = "https://ilxxwjbgrkecdvmxwlvr.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlseHh3amJncmtlY2R2bXh3bHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MjgzNjYsImV4cCI6MjA4NjAwNDM2Nn0.mWPj-lI3BYXCOCuzzH4-7A4n3rq-knJoeWLbRaYGNFk"

# Google Maps API
GOOGLE_API_KEY = "AIzaSyCws8dm1mPhPKdu4VUk7BTBEe25qGZDrb4"
